Typos and fixes
standardebooks/freeman-wills-crofts_the-cask pull request #4
Opened 2024-03-16 19:48 UTC by bentley

2024-03-17 19:33 UTC, acabal commented
I think we need to undo 4db71bf as we don't change punctuation in that way. You can fix anything that is an actual transcription error, but we don't add or remove punctuation like that.

Additionally, you fixed a quote in `‘spots’` but `‘spots’` should actually be double quoted, not single quoted.

2024-03-17 19:33 UTC, acabal requested changes

2024-03-17 19:33 UTC, acabal commented on src/epub/text/chapter-1.xhtml
> +			<p>On one side was a card label, tacked round the edges and addressed in a foreign handwriting: “<abbr>M.</abbr> Léon Felix, 141 West Jubb Street, Tottenham Court Road, London, <abbr epub:type="z3
This period is incorrect, W is a postal code in London

2024-03-28 18:45 UTC, acabal commented
I took a minute to fix these myself and merge everything in. Thanks!

2024-03-28 18:45 UTC, closed without merging

2024-03-29 20:43 UTC, bentley commented
Thanks, I got a bit distracted.